language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - py.test --cov=api

services:
  - postgresql

env:
  DB_TEST_URL = "postgresql://postgres:tony1234@localhost/test_db"

before_script:
  - psql -c 'create database stackoveflowlite;' -U postgres

after_success:
- coveralls

addons:
  postgresql: "9.5"


